name: Prueba
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checklout repo
      uses: action/

    steps:
    - name: Print a message
      run: echo "prueba"
